"use strict";
let num = 10;
let fulllName = "Subash Khatri";
console.log(num.toString());
console.log(fulllName);
let sum1 = num + 10;
console.log(sum1);
let myAge = 23;
let myfavNum = 10;
let pi = 3.21;
let negativeValue = -8;
//number cannot be assigned to a string
//let totalAge: number = myAge + "years";
let nanValue = NaN;
console.log(nanValue);
let message = "Hello, TypeScript!";
let firstName = "Subash";
let lastName = "Khatri";
let fullName = firstName + " " + lastName;
console.log(fullName);
let statement = "Hello I am learning TypeScript";
let statementLength = statement.length;
console.log(statementLength);
let text = "Text that need to be changed from lower to upper and vice versa.";
let lowercaseText = text.toLowerCase();
let uppercaseText = text.toUpperCase();
console.log(uppercaseText);
console.log(lowercaseText);
